#!/usr/bin/env bash
print_sub ()
{
    # La opcion -A1 de "grep" es para agarrar la primer linea que matchee la busqueda y la opcion -F de "awk" es el delimitador
    # Con el "awk" printf $4 se toma la columna 4 que es el tipo de DNS record
    printf "is a " ; dig "$1" | grep -A1 'ANSWER SECTION:' | awk -F' ' '{ printf $4 }'
    # Se toma la columna 5 (separada por espacios) usando "awk" - es el numero de IP
    printf " record and points to " ; dig "$1" | grep -A1 'ANSWER SECTION:' | awk -F' ' '{ printf $5 }'
    echo ""
}

if [ -z "$2" ]
then
printf "The subdomain www "
print_sub "www.$1"

printf "The subdomain lb-01 "
print_sub "lb-01.$1"

printf "The subdomain web-01 "
print_sub "web-01.$1"

printf "The subdomain web-02 "
print_sub "web-02.$1"

else
    printf "The subdomain %s " "$2" # Printeamos lo que pasen como segundo argumento
    print_sub "$2.$1"
fi
##