#!/usr/bin/env bash
#Write a Bash script that transfers a file from our client to a server:

len=$#
if [ $len -lt 4 ];
    then echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    path=$1
    ip=$2
    name=$3
    pathkey=$4
    scp -o "StrictHostKeyChecking=no" -i ./$pathkey $path $name@$ip:~/
fi


