#!/usr/bin/env bash
#Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.
sudo apt update
sudo apt -y install nginx
sudo chmod 777 /var/www/html/index.html
echo 'Hello World' | sudo tee /var/www/html/index.html
sudo touch /var/www/html/404-page.html
sudo chmod 777 /var/www/html/404-page.html
sudo echo "Ceci n'est pas une page" > /var/www/html/404-page.html
sudo sed -i '/server_name _;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo sed -i '55i error_page 404 /404-page.html;' /etc/nginx/sites-enabled/default
sudo service nginx restart