#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
sudo apt-get update && sudo apt-get upgrade
sudo apt-get -y install haproxy
sudo cp -a /etc/haproxy/haproxy.cfg{,.orig}

echo  "
listen 4385-lb-01
        bind *:80
        balance roundrobin
        server 4385-web-01 54.167.61.17:80 check
    server 4385-web-02 52.55.84.167:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy restart