#!/usr/bin/env bash
#config de load balancer
sudo apt update
sudo apt install -y haproxy

echo "listen 4375-lb-01" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "bind *:80" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "balance roundrobin" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "server 4386-web-01 54.167.61.17 check" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "server 4385-web-02 52.55.84.167 check" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo systemctl restart haproxy