#!/usr/bin/env bash
#config de load balancer
sudo apt update
sudo apt install -y haproxy
sudo nano /etc/haproxy/haproxy.cfg
echo "
frontend haproxy-main
    bind *:80
    option forwardfor  
    default_backend apache_webservers    

backend apache_webservers
    balance roundrobin
    server 03-web-01    54.167.61.17 check
    server 03-web-02    52.55.84.167 check" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo systemctl restart haproxy