#!/usr/bin/env bash
#print
num=0
while [ $num -le 9 ]
do
    if [ $num -eq 3 ];then
        echo "bad luck"
        ((num++))
        continue
    elif [[ $num -eq 7 ]]; then
        echo "good luck"
        ((num++))
        continue
    fi
    echo "Best School"
    ((num++))
done
