#!/usr/bin/env bash
#print
num=1
while [ $num -le 20 ]
do
   case $num in

  4)
    echo %num
    echo "bad luck from China"
    ((num++))
    ;;

  9)
    echo $num
    echo "bad luck from Japan"
    ((num++))
    ;;

  17)
    echo $num
    echo "bad luck from Italy"
    ((num++))
    ;;

  *)
    echo $num
    ((num++))
    ;;
esac
done
