#!/usr/bin/env bash
# Using what you did for task #1, make your fix short and sweet.
sudo apt update -y
sudo apt install ufw -y

sudo sed -i "s/IPV6=no/IPV6=yes/g" /etc/default/ufw

sudo ufw default deny incoming
sudo ufw default allow outgoing

sudo ufw allow 22 #ssh
sudo ufw allow 443 #https
sudo ufw allow 80 #http

sudo ufw enable