#!/usr/bin/env bash
#change ip local host and facebook
sudo cp /etc/hosts ~/hosts.copy
echo "127.0.0.2		localhost"> ~/hosts.copy
echo "8.8.8.8		facebook.com">> ~/hosts.copy
sudo cp -f ~/hosts.copy /etc/hosts
