#!/usr/bin/env bash
#ejecuta nginx as nginx
pkill apache2
chown nginx /etc/nginx/nginx.conf
sudo chmod 700 /etc/nginx/nginx.conf
sed -i "s /80/8080/ g" /etc/nginx/sites-enabled/default
sudo service nginx start