#!/usr/bin/env bash
#bash script that use ssh
#-b Number of bits in the created key to be created 4096
#-N The created key must be protected by the passphrase betty
#-f Name of the created private key must be school
ssh-keygen -b 4096 -f school -N betty -t rsa 